# Generated by Django 4.1.7 on 2023-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_alter_photo_images_delete_article_blog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
