# Generated by Django 4.1.7 on 2023-04-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_photo_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('hero', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('Shot', models.BooleanField(default=True)),
            ],
        ),
    ]
