# Generated by Django 4.1.7 on 2023-04-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='hero',
        ),
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.photo'),
        ),
    ]
