# Generated by Django 4.1.7 on 2023-04-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comic_hero_comic_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='image',
            new_name='photo',
        ),
    ]
