# Generated by Django 4.1.7 on 2023-04-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_image_comic_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comic',
        ),
    ]
