# Generated by Django 4.1.7 on 2023-04-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_comics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesComics',
            fields=[
                ('comics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.comics')),
            ],
            bases=('blog.comics',),
        ),
    ]
