# Generated by Django 4.1.7 on 2023-04-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_seriescomics'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='first_comics',
            field=models.BooleanField(default=False),
        ),
    ]
