# Generated by Django 4.1.7 on 2023-04-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comics_first_comics'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriescomics',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
