# Generated by Django 4.1.7 on 2023-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_seriescomics_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='author',
            field=models.BooleanField(default=False),
        ),
    ]
