# Generated by Django 4.1.7 on 2023-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_author_alter_comics_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
