# Generated by Django 4.1.7 on 2023-04-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_heros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heros',
            old_name='category',
            new_name='characters',
        ),
    ]
