# Generated by Django 4.1.7 on 2023-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_category_heros_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heros',
            name='characters',
        ),
        migrations.AddField(
            model_name='comics',
            name='characters',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
