# Generated by Django 4.1.7 on 2023-04-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_heros_characters_comics_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('comics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.comics')),
                ('heros', models.CharField(default='Other', max_length=50)),
            ],
            bases=('blog.comics',),
        ),
        migrations.RemoveField(
            model_name='comics',
            name='characters',
        ),
        migrations.DeleteModel(
            name='Heros',
        ),
    ]
