# Generated by Django 4.1.7 on 2023-04-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_characters_remove_comics_characters_delete_heros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='heros',
        ),
    ]
