# Generated by Django 4.1.7 on 2023-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_characters_heros'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='hero',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
