# Generated by Django 4.1.7 on 2023-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_characters_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='seriescomics',
            name='category',
        ),
        migrations.AddField(
            model_name='comics',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='comics',
            name='hero',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
