# Generated by Django 4.1.7 on 2023-05-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_comics_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='author',
            field=models.CharField(max_length=128),
        ),
    ]
