# Generated by Django 4.1.7 on 2023-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_comics_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='posseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comics',
            name='want',
            field=models.BooleanField(default=False),
        ),
    ]
