# Generated by Django 4.1.7 on 2023-05-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_comics_user'),
        ('authentication', '0005_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='want_set',
            field=models.ManyToManyField(blank=True, related_name='want_users', to='blog.comics', verbose_name='envie de lecture'),
        ),
    ]
